### ISSUE TITLE
Error when installing ingress for nethermind helm chart

### ISSUE THREAD

**Issue by JacqueGM** [ethpandaops/ethereum-helm-charts#137]
When configuring ingress for the nethermind helm chart version 0.3.4 I get this error 
`error calling include: template: no template \"nethermind.httpPort\" associated with template \"gotpl\"\n", "stderr_lines": ["Error: UPGRADE FAILED: template: nethermind/templates/ingress.yaml:3:16: executing \"nethermind/templates/ingress.yaml\" at <i`
I was looking at it and it seems that it's because this line is still there in the ingress template https://github.com/ethpandaops/ethereum-helm-charts/blob/nethermind-0.2.0/charts/nethermind/templates/ingress.yaml#L3  but this line has been removed from the helpers template .https://github.com/ethpandaops/ethereum-helm-charts/blob/nethermind-0.2.0/charts/nethermind/templates/_helpers.tpl#L72 

I could add a quick PR to fix  :)

**Comment by barnabasbusa** [comment]
Fixed by https://github.com/ethpandaops/ethereum-helm-charts/pull/140
