### ISSUE TITLE
Update smart-contract-verifier-http

### ISSUE THREAD

**Issue by skylenet** [ethpandaops/ethereum-helm-charts#159]

**Comment by Sledro** [comment]
@skylenet FYI this PR https://github.com/blockscout/blockscout-rs/pull/340 changes the service port number from 8043 to 8050 so this chart currently gets stuck in a restart loop. Liveness probe cannot find the service on 8043 anymore.

Thanks!

**Comment by skylenet** [comment]
> 

Thank you. That was helpful. It seems like they accidentally forgot to also update a bunch of config files and docker examples that they provide within the same repo. Could be worth to make a PR for that on https://github.com/blockscout/blockscout-rs/ .

The helm chart should work again now 🙏  Sorry for the delay on fixing this.
