### ISSUE TITLE
prysm v4.0.8

### ISSUE THREAD

**Issue by PippinAintEasy-B** [ethpandaops/ethereum-helm-charts#225]
Hey just wondering when you will update your dockerhub prysm image to version 4.0.8

Best regards

**Comment by PippinAintEasy-B** [comment]
Oh thank you very much.

And Thanks for the quick answer!

**Comment by skylenet** [comment]
@Savid is this something we can easily add? Trigger a build whenever prysm makes a release? Basically watching for `vX.Y.Z` in their repo tags: https://github.com/prysmaticlabs/prysm/tags (Wouldn't bother about other tags, e.g. the alpha suffixed ones)

**Comment by barnabasbusa** [comment]
The upstream images are now compatible with our helm charts.
