### ISSUE TITLE
Question: How to run erigon private network?

### ISSUE THREAD

**Issue by trungdlp-wolffun** [ethpandaops/ethereum-helm-charts#292]
I'm currently exploring running a private network using Erigon, but I'm encountering some challenges. Could someone provide guidance or a step-by-step tutorial on how to set up and run an Erigon private network?

Specifically, I'm looking for details on:

1. Installation: How to install Erigon and any prerequisites.
2. Configuration: Guidance on configuring Erigon for a private network setup.
3. Genesis Block: Steps to create a genesis block for the private network.
4. Running the Network: Instructions on starting and managing the private network.
5. Troubleshooting: Common issues that might arise and how to resolve them.

Any additional tips, best practices, or resources would also be greatly appreciated. Thank you in advance for your assistance!

**Comment by barnabasbusa** [comment]
I'd recommend you to check out this repo: https://github.com/kurtosis-tech/ethereum-package

Ethereum-helm-charts is really the wrong repo for this question. You might want to take a look first in the repo mentioned above, and if you still have some issues/difficulties launching a private devnet, then please an issue there.

**Comment by trungdlp-wolffun** [comment]
Thanks a lot of @barnabasbusa
